### ISSUE TITLE
feature requestion - reuse existing mesh when mesh clone exists already

### ISSUE THREAD

**Issue by zeffii** [zeffii/MeshCloneRestore#2]
mtrcol asks:

> may i ask you for "deleting cloned object" feature ? if there is already cloned object,if i import from another json file, the new cloned object (that i'm importing) does not replace the existing cloned object 

not sure.. probably easy but i'm busy right now

**Comment by zeffii** [comment]
yes. delete clone is super simple.

**Comment by zeffii** [comment]
``` python

def delete_clone():

    meshes = bpy.data.meshes
    ob = bpy.context.active_object
    if ob and (ob.name +  '_clone') in meshes:
        clone_name = ob.name +  '_clone'
        try:
            meshes.remove(meshes[clone_name])
            print('Mesh: {0} removed'.format(clone_name))
        except:
            print('failed to remove clone [ {0} ]..panic ! '.format(clone_name))

```

**Comment by navmesh** [comment]
Thank you very much, i 'll try it

**Comment by zeffii** [comment]
the code isn't included in the add-on yet, but you are welcome to experiment with adding it yourself.

**Comment by navmesh** [comment]
thank you millions time ,it works like a charm:)

**Comment by zeffii** [comment]
added icon + operator button for this process. Will now show up in the UI when (and only when) the Object currently active has a clone called Object.name + `_clone` in Meshes.

![image](https://cloud.githubusercontent.com/assets/619340/11762617/f4c987e6-a0eb-11e5-885b-d36d45661e7b.png)

**Comment by navmesh** [comment]
Thank you very much :)

**Comment by zeffii** [comment]
no sweat. let me see what you make with these features some day :)

**Comment by navmesh** [comment]
sure :) your script is very helpful ,it saves my time
thank you very much :)
